# Generated by Django 4.2.17 on 2024-12-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoughToMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coughaudio',
            name='file',
            field=models.FileField(upload_to='media/raw_audios/'),
        ),
    ]
