# Generated by Django 4.2.17 on 2024-12-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoughToMusic', '0002_alter_coughaudio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coughaudio',
            name='status',
        ),
        migrations.AddField(
            model_name='coughaudio',
            name='cough_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coughaudio',
            name='is_cough_detected',
            field=models.BooleanField(default=False),
        ),
    ]
